### PR TITLE
Fixes #2278: Improve OAuth2Resource2 log messages during communication error with Authorization Server.

### LINKED ISSUE #2278: improve OAuth2 log: connection problem while contacting AuthorizationServer
```
{"@timestamp":"2025-10-29T15:49:59.544Z","ecs.version":"1.2.0","log.level":"ERROR","message":"Could not exchange code for token.","process.thread.name":"router /1.1.1.1:1000","log.logger":"com.predic8.membrane.core.interceptor.oauth2client.rf.OAuth2CallbackRequestHandler","api":"...","error.type":"java.net.SocketException","error.message":"Connection reset","error.stack_trace":"java.net.SocketException: Connection reset\n\tat java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318)\n\tat java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)\n\tat java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)\n\tat java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)\n\tat java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489)\n\tat java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483)\n\tat java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)\n\tat java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)\n\tat java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)\n\tat java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)\n\tat java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)\n\tat java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)\n\tat com.predic8.membrane.core.transport.ssl.StaticSSLContext.createSocket(StaticSSLContext.java:407)\n\tat com.predic8.membrane.core.transport.http.Connection.open(Connection.java:112)\n\tat com.predic8.membrane.core.transport.http.ConnectionManager.getConnection(ConnectionManager.java:136)\n\tat com.predic8.membrane.core.transport.http.HttpClient.call(HttpClient.java:241)\n\tat com.predic8.membrane.core.transport.http.HttpClient.call(HttpClient.java:207)\n\tat com.predic8.membrane.core.interceptor.oauth2.authorizationservice.AuthorizationService.doRequest(AuthorizationService.java:210)\n\tat com.predic8.membrane.core.interceptor.oauth2.authorizationservice.AuthorizationService.codeTokenRequest(AuthorizationService.java:340)\n\tat com.predic8.membrane.core.interceptor.oauth2client.rf.OAuth2CallbackRequestHandler.handleRequest(OAuth2CallbackRequestHandler.java:105)\n\tat com.predic8.membrane.core.interceptor.oauth2client.OAuth2Resource2Interceptor.handleRequestInternal(OAuth2Resource2Interceptor.java:155)\n\tat com.predic8.membrane.core.interceptor.AbstractInterceptorWithSession.handleRequest(AbstractInterceptorWithSession.java:66)\n\tat com.predic8.membrane.core.interceptor.FlowController.invokeRequestHandlers(FlowController.java:81)\n\tat com.predic8.membrane.core.interceptor.UserFeatureInterceptor.handleRequest(UserFeatureInterceptor.java:37)\n\tat com.predic8.membrane.core.interceptor.FlowController.invokeRequestHandlers(FlowController.java:81)\n\tat com.predic8.membrane.core.transport.http.AbstractHttpHandler.invokeHandlers(AbstractHttpHandler.java:52)\n\tat com.predic8.membrane.core.transport.http.HttpServerHandler.process(HttpServerHandler.java:284)\n\tat com.predic8.membrane.core.transport.http.HttpServerHandler.processHttp1Request(HttpServerHandler.java:218)\n\tat com.predic8.membrane.core.transport.http.HttpServerHandler.processSingleRequest(HttpServerHandler.java:191)\n\tat com.predic8.membrane.core.transport.http.HttpServerHandler.run(HttpServerHandler.java:102)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\n"}
```

### PR DESCRIPTION
**Pull request by rrayst**
## Summary by CodeRabbit

* **Bug Fixes**
  * Improved error handling for OAuth2 token operations with standardized error responses instead of raw exceptions.
  * Enhanced token refresh exception handling to ensure consistent error reporting across OAuth2 workflows.

### CODE REVIEW

File: core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/authorizationservice/AuthorizationService.java [hunk 1]
```diff
@@ -323,23 +330,43 @@ public InputStream resolve(ResolverMap rm, String baseLocation, String url) thro
...
-                new Request.Builder().post(getTokenEndpoint(fc))
-                        .contentType(APPLICATION_X_WWW_FORM_URLENCODED)
-                        .header(ACCEPT, APPLICATION_JSON)
-                        .header(USER_AGENT, USERAGENT),
-                refreshTokenBodyBuilder(refreshToken).scope(wantedScope), fc)
-                .buildExchange())));
+        Response response;
+        try {
+            response = doRequest(applyAuth(
+                    new Request.Builder().post(getTokenEndpoint(fc))
```
Comment (predic8) [inline core/src/main/java/com/predic8/membrane/core/interceptor/oauth2/authorizationservice/AuthorizationService.java:336]: Request or RequestBuild has a static method post so new is not needed

**Review by predic8 — APPROVED** [review]
